### ISSUE TITLE
2014 Port of Motor class

### ISSUE THREAD

**Issue by georgetzavelas** [FRC2994/FRC-2015#4]
Using the Motor class from 2014 as an example create a Motor class that can use all kinds of Motors: Talon, Victor, Jaguar, TalonSRX, VictorSRX.

The inputs to the constructor are the PWM channel and the motor type.

The motor types should be defined per motor in the constants file.

Test with different motors on the new PlyBoy

**Comment by JackMc** [comment]
Sounds like a great idea! Would you pass in the type of motor at runtime? I'm at home because I don't want to make y'all sick but will be there tomorrow

**Comment by Patadorea** [comment]
Hope you feel better soon Jack! I just finished the class and will push it when I finish some of the other issues.

**Comment by JackMc** [comment]
Done. Closed by @Patadorea #8
